import java.util.Properties

plugins {
    id("com.android.application")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

// Release signing details, kept out of the repository.
//
// `android/key.properties` is gitignored, as is the keystore it points at: a
// signing key is the app's identity on Play, and anyone holding it can publish
// an update users will install without question. Create it with the command in
// README.md; it is never generated by a script and never committed.
val keystoreProperties = Properties().apply {
    val file = rootProject.file("key.properties")
    if (file.exists()) {
        file.inputStream().use { load(it) }
    }
}
val hasReleaseKey = keystoreProperties.getProperty("storeFile") != null

if (!hasReleaseKey) {
    // println, not logger.warn: Flutter's gradle wrapper swallows warn-level
    // output, so the one line that says this artifact cannot be published
    // would never reach the person building it.
    println(
        "Wanderlock: no android/key.properties — a release build here is signed " +
            "with the DEBUG key and cannot be published. See README.md."
    )
}

android {
    namespace = "com.wanderlock.wanderlock"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        // Held stable even if the brand name changes — see the note at the top
        // of README.md. Changing it after release orphans every install.
        applicationId = "com.wanderlock.wanderlock"
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    signingConfigs {
        if (hasReleaseKey) {
            create("release") {
                storeFile = rootProject.file(keystoreProperties.getProperty("storeFile"))
                storePassword = keystoreProperties.getProperty("storePassword")
                keyAlias = keystoreProperties.getProperty("keyAlias")
                keyPassword = keystoreProperties.getProperty("keyPassword")
            }
        }
    }

    buildTypes {
        release {
            // Falls back to the debug key rather than failing the build: a
            // contributor without the keystore must still be able to run a
            // release build locally. The line printed above is what keeps that
            // fallback from being mistaken for a publishable artifact.
            signingConfig = if (hasReleaseKey) {
                signingConfigs.getByName("release")
            } else {
                signingConfigs.getByName("debug")
            }
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

flutter {
    source = "../.."
}
